name: Lint

permissions:
  contents: read

concurrency:
  group: lint-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git clone --filter=blob:none --depth=200 "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}" .
          git checkout "${{ github.sha }}"

      - name: Set up Go
        run: |
          ./install_golang.sh

      - name: Test
        run: |
          go run ./lint
          go test ./shared/... ./lint/... -count=1 -race
